---
# Ansible playbook for a docker single.
#
#
# @author Patricio López (2019).

- hosts: all
  gather_facts: yes

  vars_files:
    - host_vars/remote


  pre_tasks:
  tasks:
    - name: Install a list of packages
      become: yes
      yum:
              name:
                      - epel-release
                      - python-pip
              lock_timeout: 180
              state: present
    - name: Install docker-compose
      become: yes
      command: pip install docker-compose
