all:
        hosts:
                remote:
                        ansible_connection: ssh
                        ansible_user: vagrant
                        ansible_host: 10.32.72.100 #manager
                        ansible_port: 22
                        ansible_ssh_private_key_file: /home/plopez/examenDevOps/docker-swarm/.vagrant/machines/manager/virtualbox/private_key
