---
# Ansible playbook for a docker single.
#
#
# @author Patricio López (2019).

- hosts: all
  gather_facts: yes

  vars_files:
    - host_vars/remote


  pre_tasks:
  tasks:
    - name: Install a list of packages
      become: yes
      yum:
              name:
                      - yum-utils
                      - net-tools
                      - device-mapper
                      - device-mapper-persistent-data
                      - lvm2
              lock_timeout: 180
              state: present
