---
# Ansible playbook for a docker single.
#
#
# @author Patricio López (2019).

- hosts: all
  gather_facts: yes

  vars_files:
    - host_vars/remote


  pre_tasks:
  tasks:
          - name: create volume portainer_data
            command: docker volume create portainer_data
          - name: run portainer
            command: docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
          - name: get portainer-agent-stack.yml
            command: curl -L https://downloads.portainer.io/portainer-agent-stack.yml -o portainer-agent-stack.yml
          - name: stack deploy
            command: docker stack deploy --compose-file=portainer-agent-stack.yml portainer
