---
- name: purge docker-compose package
  yum:
          name: docker-compose
          become: yes
          state: removed
- name: install needed packages
  yum:
          name:
                  - yum-utils
                  - net-tools
                  - device-mapper
                  - device-mapper-persistent-data
                  - lvm2
          become: yes
          lock_timeout: 180
          state: present

- name: Install pip
  yum:
          name:  python-pip
          become: yes
          state: present
